version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
  
  web_old:
    container_name: web_old
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./web_old.conf:/etc/nginx/conf.d/default.conf
      - ./old.html:/usr/share/nginx/html/index.html

  web_new:
    container_name: web_new
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./web_new.conf:/etc/nginx/conf.d/default.conf
      - ./new.html:/usr/share/nginx/html/index.html